version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "5001:5001"  # Expose port 5001 from the container to the host
    env_file:
      - .env  # Load environment variables from the .env file
    command: npm run start:prod  # Command to start the app in production mode
    restart: always  # Ensure the container restarts if it stops
