# version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Match the PORT from your .env file
    volumes:        # For hot-reloading during development(optional, not need in production)
      - .:/app
      - /app/node_modules
    env_file:
      - .env # Specify your .env file
    # command: npm run start:dev # Or your relevant start script
    command: npm run start:prod # Or your relevant start script
    restart: always
